### ISSUE TITLE
Questions about encoding?

### ISSUE THREAD

**Issue by tql-code** [HengyiWang/Co-SLAM#8] opened 2023-06-08 15:19 UTC
Thank you for sharing your excellent work！
But I have a question about your implementation of hash encoding. In model/encodings.py, you wrote this code to achieve the allocation of multiple resolutions:
per_level_scale = np.exp2(np.log2(desired_resolution  / n_levels) / (n_levels - 1))
But I found that the settings for this instant-ngp are not the same, you did not use N_ Min for calculation. May I ask how to understand this code?
I would be very grateful if you could explain this code

**Comment by HengyiWang** [comment] 2023-06-08 15:52
Hi @tql-code, thank you for your question. I apologize for the confusion caused by the code snippet you mentioned. There is a typo, and the correct code should be:

https://github.com/HengyiWang/Co-SLAM/blob/1049b2b06d83068f4254ceab04f869f8eb318a7e/model/encodings.py#L33

Since the base_resolution and n_levels were both set to 16 in our setting, this typo did not cause any difference and thus went unnoticed during the development. Sorry for that. 

I appreciate you bringing it to my attention. I have now fixed the issue and pushed the latest version to the GitHub repository. If you have any further questions or concerns, please feel free to let me know:)

**Closed** 2023-07-21 22:07 UTC
